### ISSUE TITLE
Suggestion for php prerequisites

### ISSUE THREAD

**Issue by menteora** [hechoendrupal/drupal-console-book#133]
Hi I've solved this issue:

```
[+] Downloading Drupal 8.0.0
[+] Unable to open /tmp/drupal.H9qBxktar.gz using mode r+: fopen(/tmp/drupal.H9qBxktar.gz): failed to open stream: No such file or directory
```

watching a conversation under: https://gitter.im/hechoendrupal/DrupalConsole?at=565e0bce65c2a5b027d72ba7

I think it's a good idea to reccomend php5-curl prerequisite under documentation

Regards
menteora

**Comment by jmolivas** [comment]
@menteora: I will add this to the docs.

**Comment by jmolivas** [comment]
We recently added the `check` command to validate system requirements, we must add this the docs.

![drupal-check](https://cloud.githubusercontent.com/assets/366275/13660407/8cf65b60-e63e-11e5-9a40-4994b3160991.png)
