### ISSUE TITLE
[docs] Add homebrew-php as installation option

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console-book#179]
### Problem / Motivation

Since this issue is been solve - https://github.com/Homebrew/homebrew-php/issues/2665#event-524049582 . Users can get DrupalConsole if they have homebrew + homebrew-php.
### Solution

We should document somewhere in the DC book that it can be install with homebrew-php.

**Comment by jmolivas** [comment]
@darol100: Are we planning to maintain brew? we should automate that via travis?

**Comment by darol100** [comment]
@jmolivas , I think we should automate. Shall we create an issue to create this in Travis ? I hope that the people from Homebrew-php do not hate us, because all of PR's.
