### ISSUE TITLE
Note mentions -y argument, but sample code contains -n

### ISSUE THREAD

**Issue by balagan73** [hechoendrupal/drupal-console-book#190]
On page 33 both sample code contains -n parameter, but the note says: 

> In this example code, we accept all interactive questions, i.e. answering “yes” when passing the -y argument.

I think note should match the sample code.

**Comment by balagan73** [comment]
Running help for other commands I see that -n means --no-interaction so maybe the note should just mention the -n argument

**Comment by jmolivas** [comment]
@balagan73 is this the link you are referencing?
- Link: https://hechoendrupal.gitbooks.io/drupal-console/content/en/contributing/project-requirements.html

- Source: https://github.com/hechoendrupal/drupal-console-book/blob/master/en/contributing/project-requirements.md#start-the-phps-built-in-server

**Comment by jmolivas** [comment]
- I think we should change this text:

**NOTE:** Make sure you use your own user and database credentials when running `site:install` and never user root on production. In this example code, we accept all interactive questions, i.e. answering *“yes”* when passing the `-y` argument.

- To read as:

**NOTE:** Make sure you use your own user and database credentials when running `site:install` and never user root on production. In this example code, we accept skip any interactive questions, by passing the `-n` option.

**Comment by balagan73** [comment]
Yes, the example contains the -n argument, the note mentions -yes, for me
it is confusing.

2016-03-10 7:03 GMT+01:00 Jesus Manuel Olivas <notifications@github.com>:

**Comment by jmolivas** [comment]
No longer applies
