### ISSUE TITLE
Rewrite the What is the Drupal Console page to more fully explain he capabilities of Console.

### ISSUE THREAD

**Issue by carsonblack** [hechoendrupal/drupal-console-book#255]
Console has the ability to do more than generate code.

**Comment by carsonblack** [comment]
I am currently working on this

**Comment by jmolivas** [comment]
@carsonblack  I updated the description https://docs.drupalconsole.com/en/about/what-is-the-drupal-console.html

There is probably more work to do but at least is mentioning the other capabilities of DrupalConsole besides code generation.
