### ISSUE TITLE
Temporarily mark site:mode command as unavailable.

### ISSUE THREAD

**Issue by carsonblack** [hechoendrupal/drupal-console-book#260]
Docs currently have documentation for the site:mode command https://docs.drupalconsole.com/en/commands/site-mode.html. In the current releases this is not an available command, although it appears this command will return later. Might be a good idea to mark this command as currently unavailable in the documentation so as to not create any confusion for users.

**Comment by jmolivas** [comment]
The `site:mode` command is back too.
