### ISSUE TITLE
Temporarily mark site:new command as unavailable

### ISSUE THREAD

**Issue by carsonblack** [hechoendrupal/drupal-console-book#261]
Docs currently have documentation for the site:new command https://docs.drupalconsole.com/en/commands/site-new.html. In the current release this is not an available command. Presumably this was caused by the changes to the launcher. Might be a good idea to mark this command as currently unavailable in the documentation so as to not create any confusion for users.

**Comment by jmolivas** [comment]
The `site:new` command is back ;)
