### ISSUE TITLE
downloading the launcher doesn't work

### ISSUE THREAD

**Issue by joachim-n** [hechoendrupal/drupal-console-book#262]
I get this output:

`
$ curl http://drupalconsole.com/installer -L -o drupal.phar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
`

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening.
