### ISSUE TITLE
Add descriptive text to composer install page

### ISSUE THREAD

**Issue by bradbulger** [hechoendrupal/drupal-console-book#390]
The steps on https://docs.drupalconsole.com/en/getting/composer.html are not clear. Are we supposed to both do a require - presumably inside an existing composer project? - AND create a project? If so, how do the two steps relate? If we are meant to do one or the other, do any of the other steps on the page apply to both, or only one, or ?

What is the thinking behind these commands, what is it that they are intended to accomplish?

**Comment by harold20** [comment]
thanks @bradbulger
