### ISSUE TITLE
Determine way to automate maintaining SUMMARY.md

### ISSUE THREAD

**Issue by LowellMontgomery** [hechoendrupal/drupal-console-book#52]
It should not be hard to iterate the files and build such a links page programmatically... a simple script could automate the process. Maybe you have a nifty, Symphony-powered approach or trick you have already used? If so, we should document that. If not, we should find something (or write something) and use it.

**Comment by jmolivas** [comment]
Probably won't be that complex to create a script to iterate the directories and scan md files extract h1 `#` to generate the links, we may need to rename files as 01_ to set the order of the links within a directory.

**Comment by LowellMontgomery** [comment]
Right... just what I was thinking.

 We could even have a standard that anything directly under the H1 could be taken as a "page synopsis" that could be used as the link title (for better UX / SEO, i.e. so people more easily find what they want).

Even cooler might be to also parse H2s and allow jumping directly to them... on pages where there is enough information that this could be useful. I'll create a new branch for the few necessary file changes. Then I'll look for an existing script or write one and share it... it might be useful for other projects, but that thought suddenly seems so true that I'm sure it must exist already, which could allow us to continue to build on "proudly found elsewhere". ;-)

**Comment by jmolivas** [comment]
@LowellMontgomery: I am planning to add a new command that takes advantage of PR https://github.com/hechoendrupal/DrupalConsole/pull/868 I mentioned on the other issue https://github.com/hechoendrupal/drupal-console-book/issues/53

This command will iterate each one of the commands and generate both 
Index
https://github.com/hechoendrupal/drupal-console-book/blob/master/commands/available-commands.md
And each command page 
https://github.com/hechoendrupal/drupal-console-book/tree/master/commands

I can add some logic to read the repo files and generate the Summary file as well
https://github.com/hechoendrupal/drupal-console-book/blob/master/SUMMARY.md

**Comment by jmolivas** [comment]
Summary section related to Available Commands is now automatically generated by the new `generate:doc`command.

**Comment by jmolivas** [comment]
@LowellMontgomery Closing this one, feel to open or create a another issue for new ideas for improvement the doc automation.
