### ISSUE TITLE
Figure out a script to maintain the "how to use" command documentation

### ISSUE THREAD

**Issue by LowellMontgomery** [hechoendrupal/drupal-console-book#53]
As commands/arguments/options are added and changed, maintaining the "how to use" section of the documentation will inevitably get tricky and the documentation will get outdated and possibly full of inaccuracies. A simple script (in the Drupal Console project) could output all the "how to use" files as Markdown, ensuring all commands are documented and include all current arguments and options. This issue is to discuss pro/cons of this and a most suitable approach.

Other thoughts: Maybe a new command: `drupal generate:documentation` ... It could output .md files to a selected directory.

**Comment by jmolivas** [comment]
This sounds interesting, we can create a few twig templates and render the available commands md files.

**Comment by LowellMontgomery** [comment]
Right... I was thinking about it during the initial copy/paste/format repetition: "surely we can automate this" ;-)

Maybe the documentation and project could be in one repository for this to be most ideally implemented?  Command/API documentation could be re-generated (perhaps even automagically) whenever the commands are updated or new ones added. I'm not yet the Git geek some are, so I'm not sure how to implement it, but then the command documentation could be in both repositories (the "book" and the actual Console), included in one from the other. Having the most critical "API docs" in the same repository as the Console could also just be handy for users.

**Comment by jmolivas** [comment]
@LowellMontgomery I just send a PR https://github.com/hechoendrupal/DrupalConsole/pull/868, This PR provides a new --generate-doc option to automate documentation generation.

![--generate-doc](https://cloud.githubusercontent.com/assets/366275/9844669/f6b57136-5a79-11e5-8abc-17f56db04834.png)

**Comment by jmolivas** [comment]
I sent another PR https://github.com/hechoendrupal/DrupalConsole/pull/877 this one includes the `generate:doc` command, this command iterate each DrupalConsole core command and generates the proper Markdown files.

You must run the `generate:doc` command within a Drupal 8 installation.
```
$ console.dev generate:doc --path=/path/to/your/repo/drupal-console-book/
``

**Comment by jmolivas** [comment]
Cosidered closed since `generate:doc:gitbook` command is working properly
